[package]
name = "juniper"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = "1.9.2"
once_cell = "1.12.0"
derive-new = "0.5.9"
juniper = "0.15"
actix-web = "4"
actix-cors = "0.6.4"
env_logger = "0.10.0"